/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCallsRouteImport } from './routes/api/calls'
import { Route as ApiOffersEvaluateRouteImport } from './routes/api/offers/evaluate'
import { Route as ApiLoadsSearchRouteImport } from './routes/api/loads/search'
import { Route as ApiCarriersVerifyRouteImport } from './routes/api/carriers/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsRoute = ApiCallsRouteImport.update({
  id: '/api/calls',
  path: '/api/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOffersEvaluateRoute = ApiOffersEvaluateRouteImport.update({
  id: '/api/offers/evaluate',
  path: '/api/offers/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadsSearchRoute = ApiLoadsSearchRouteImport.update({
  id: '/api/loads/search',
  path: '/api/loads/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarriersVerifyRoute = ApiCarriersVerifyRouteImport.update({
  id: '/api/carriers/verify',
  path: '/api/carriers/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/carriers/verify': typeof ApiCarriersVerifyRoute
  '/api/loads/search': typeof ApiLoadsSearchRoute
  '/api/offers/evaluate': typeof ApiOffersEvaluateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/carriers/verify': typeof ApiCarriersVerifyRoute
  '/api/loads/search': typeof ApiLoadsSearchRoute
  '/api/offers/evaluate': typeof ApiOffersEvaluateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/carriers/verify': typeof ApiCarriersVerifyRoute
  '/api/loads/search': typeof ApiLoadsSearchRoute
  '/api/offers/evaluate': typeof ApiOffersEvaluateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/calls'
    | '/api/carriers/verify'
    | '/api/loads/search'
    | '/api/offers/evaluate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/calls'
    | '/api/carriers/verify'
    | '/api/loads/search'
    | '/api/offers/evaluate'
  id:
    | '__root__'
    | '/'
    | '/api/calls'
    | '/api/carriers/verify'
    | '/api/loads/search'
    | '/api/offers/evaluate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCallsRoute: typeof ApiCallsRoute
  ApiCarriersVerifyRoute: typeof ApiCarriersVerifyRoute
  ApiLoadsSearchRoute: typeof ApiLoadsSearchRoute
  ApiOffersEvaluateRoute: typeof ApiOffersEvaluateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls': {
      id: '/api/calls'
      path: '/api/calls'
      fullPath: '/api/calls'
      preLoaderRoute: typeof ApiCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offers/evaluate': {
      id: '/api/offers/evaluate'
      path: '/api/offers/evaluate'
      fullPath: '/api/offers/evaluate'
      preLoaderRoute: typeof ApiOffersEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loads/search': {
      id: '/api/loads/search'
      path: '/api/loads/search'
      fullPath: '/api/loads/search'
      preLoaderRoute: typeof ApiLoadsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carriers/verify': {
      id: '/api/carriers/verify'
      path: '/api/carriers/verify'
      fullPath: '/api/carriers/verify'
      preLoaderRoute: typeof ApiCarriersVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCallsRoute: ApiCallsRoute,
  ApiCarriersVerifyRoute: ApiCarriersVerifyRoute,
  ApiLoadsSearchRoute: ApiLoadsSearchRoute,
  ApiOffersEvaluateRoute: ApiOffersEvaluateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
